package org.springproject.bloodbank.model;


import org.springproject.bloodbank.dao.DataBaseDAO;
import org.springproject.bloodbank.dto.UserDTO;

import java.io.Serializable;
import java.time.LocalDate;


public class User implements Serializable {
    public final String securityCode;
    private final int id; // Creating a id based on the hashcode generated by the
    private final String bloodGroup;
    private final String name;
    private final LocalDate dateOfBirth;
    private final String email;
    private final String role;
    public boolean locked = false;
    public int chances = 4;
    // localdate instance
    private String password;

    public User(UserDTO userDTO) {
        this.name = userDTO.getName();
        this.email = userDTO.getEmail();
        this.dateOfBirth = userDTO.getDateOfBirth();
        this.password = userDTO.getPassword();
        this.role = userDTO.getRole();
        this.id = this.hashCode();
        this.bloodGroup = userDTO.getBloodGroup();
        this.chances = userDTO.chances;
        this.locked = userDTO.locked;
        this.securityCode = userDTO.securityCode;
    }

    public String getSecurityCode() {
        return securityCode;
    }

    public boolean isLocked() {
        return locked;
    }

    public int getChances() {
        return chances;
    }

    public int getId() {
        return id;
    }

    public String getBloodGroup() {
        return bloodGroup;
    }

    public String getRole() {
        return role;
    }

    @Override
    public String toString() {
        return "User{" +
                "securityCode='" + securityCode + '\'' +
                ", id=" + id +
                ", bloodGroup='" + bloodGroup + '\'' +
                ", name='" + name + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", email='" + email + '\'' +
                ", role='" + role + '\'' +
                ", locked=" + locked +
                ", chances=" + chances +
                ", password='" + password + '\'' +
                '}';
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        DataBaseDAO.saveArrayListToFile(DataBaseDAO.getUsers());
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public String getEmail() {
        return email;
    }
}
